### ISSUE TITLE
Misc //TODOs, and other cleanup

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/MCMergeManager#92]
This is basically a running TODO list for me. Though some of these need students to be involved.

- [x] Fix the Theme rendering errors
- [x] Delete the package `stronghold2016`, deal with whatever compile errors that creates.
- [x] Couple all strings "http://ftp.team2706.ca:3000/..." to the SharedPreferences #86 #76 
- [x] Go through all // TODO markers
- [x] TeamInfoFragment crashes when you load a team.
- [x] Remove xml layouts from `stronghold2016`
- [x] Remove Help page?
- [x] Update About string?
- [x] Cleanup main page - Nathan
- [x] MainActivity: change "Event:" bar to the human-readable event name?
- [x] Port all imports to `stronghold2016` over to `steamworks2017`. I left the ones in the Match Scouting Pages as an activity for Justin #53.
- [x] `MatchSchedule.java`: //TODO match 3 never has a score, for testing match prediction.
- [x] Deal with #6 
- [x] Deal with #58: remove the stronghold-related stuff
- [x] Figure out why the match schedule is not pulling properly from TBA
- [x] Figure out how to get Danny an instance of FileUtils.
- [x] Remove Keypad from appearing on app startup

**Comment by ounsworth** [comment]
Deal with #6

**Comment by wall-daniel** [comment]
[ ] - Get rid of stuff in the data objects that are not being used at the moment ( for example int x and int y for FuelShotEvent)
